version: '3.8'

services:
  playwright-tests:
    build:
      context: .
    depends_on:
      - react-app
    environment:
      - REACT_APP_SERVER_URL=http://react-app:3000  # URL for the React app within the Docker network

networks:
  default:
    external:
      name: react_playwright_network
