version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
        environment:
          - CI: true
    steps:
      - checkout
      - setup_remote_docker
      # Other steps for installing dependencies, etc.
      - run:
          name: Run Playwright tests
          command: npm test  # or the command to run your Playwright tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
